### ISSUE TITLE
pagify is not a function

### ISSUE THREAD

**Issue by outOFFspace** [colintoh/sails-hook-pagify#2]
Have an error 
`TypeError: City.pagify is not a function`

`City.pagify('city', {
    populate: ['region'],
    page: 1,
    perPage: 10 // Overwrite the project-wide settings
}).then(function(data) {
        console.log('data', data);
}).catch(function(err) {
        // err.Errors contains the error messages
});`

**Comment by jntramosbonilla** [comment]
what version of Sails are you using? this module doesn't work on sails v0.12 or above.

**Comment by howardEagle** [comment]
v0.12.3, will you implement for this version?

**Comment by paataD** [comment]
I have the same error too 0.12.3 ver

**Comment by colintoh** [comment]
Merged PR -  https://github.com/colintoh/sails-hook-pagify/pull/1
